version: "3.9"

services:
  backend-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: backend-dev
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  backend-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: backend-prod
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
