name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # manual trigger option

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Backend dependencies (use npm ci)
      - name: Install backend dependencies
        run: npm ci --prefix backend

      # Frontend dependencies (use npm install to avoid lock issues)
      - name: Install frontend dependencies
        run: npm install --prefix frontend

      # Build backend (dummy build we added)
      - name: Build backend
        run: npm run build --prefix backend

      # Build frontend
      - name: Build frontend
        run: npm run build --prefix frontend        run: npm run build --prefix frontend
