- name: Install backend dependencies
  run: |
    cd backend
    npm install

- name: Build backend
  run: |
    cd backend
    npm run build

- name: Install frontend dependencies
  run: |
    cd frontend
    npm install

- name: Build frontend
  run: |
    cd frontend
    npm run build
